name: flutter_tags_x
description: Creating selectable and input tags (TextField) has never been easier.
version: 1.1.0
homepage: https://github.com/avdosev/flutter_tags/
repository: https://github.com/avdosev/flutter_tags/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
